os: osx

addons:
    homebrew:
      packages:
        - cmake
        - vtk
      update: true

script:
  - mkdir -p build/
  - cd build/
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF .. && make -j

language: cpp
cache: ccache
